import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("birthday room source has product UI and no starter preview", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const room = await readFile(new URL("../app/BirthdayRoom.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const playlist = JSON.parse(await readFile(new URL("../public/music/playlist.json", import.meta.url), "utf8"));

  assert.match(page, /NEXT_PUBLIC_BIRTHDAY_NAME/);
  assert.match(page, /NEXT_PUBLIC_BIRTHDAY_NAME \?\? "Trần Thế"/);
  assert.match(layout, /NEXT_PUBLIC_BIRTHDAY_NAME \?\? "Trần Thế"/);
  assert.match(layout, /window\.zaloJSV2/);
  assert.match(layout, /vite-error-overlay/);
  assert.match(room, /Các hành động/i);
  assert.match(room, /birthday-intro-title/);
  assert.match(room, /birthday-portrait\.webp/);
  assert.match(room, /Vào sân khấu sinh nhật/);
  assert.match(styles, /\.birthday-intro/);
  assert.match(room, /avatar-sprites-v7\.png/);
  assert.match(styles, /--sprite-sheet/);
  assert.match(room, /20 avatar · 10 nam · 10 nữ/);
  assert.match(room, /room-info/);
  assert.match(room, /Nhảy theo nhạc/);
  assert.match(room, /DANCE_PROFILES/);
  assert.match(room, /Điệu riêng/);
  assert.equal(room.match(/animation: "signature-/g)?.length, 20);
  assert.equal(styles.match(/@keyframes signature-(?!(?:shadow|symbol|frames-))/g)?.length, 20);
  assert.equal(styles.match(/@keyframes signature-frames-/g)?.length, 20);
  assert.equal(new Set([...room.matchAll(/symbol: "([^"]+)"/g)].map((match) => match[1])).size, 20);
  const signatureSpeeds = [...room.matchAll(/symbol: "[^"]+", speed: (\d+)/g)].map((match) => Number(match[1]));
  assert.equal(signatureSpeeds.length, 20);
  assert.ok(signatureSpeeds.every((speed) => speed >= 1500));
  const signatureMotion = styles.slice(styles.indexOf("@keyframes signature-coral"), styles.indexOf("@keyframes action-sparkle"));
  assert.doesNotMatch(signatureMotion, /skew|rotateY|perspective|scaleX|scaleY|scale\([^)]*,/);
  assert.doesNotMatch(room, /🤖|Robot Pop/);
  const actionSets = [...room.matchAll(/\w+: \{ frames: \[([^\]]+)\], idleFrame: ([0-3]), tempo: ([\d.]+), travel: (\d+), lift: (\d+), tilt: (\d+), stretch: ([\d.]+), direction: (-?1) \}/g)];
  assert.equal(actionSets.length, 20);
  assert.equal(new Set(actionSets.map((match) => match.slice(1).join("|"))).size, 20);
  assert.equal(new Set(actionSets.map((match) => match[1])).size, 20);
  assert.equal(new Set(actionSets.map((match) => match[2])).size, 4);
  assert.match(styles, /@keyframes character-idle/);
  assert.match(styles, /@keyframes character-action-frames/);
  assert.match(styles, /var\(--action-speed\)/);
  assert.match(room, /wave: \[0, 1, 0, 1\]/);
  assert.match(room, /ACTION_FRAME_ORDERS\[action\]\.map\(\(frame\) => SPRITE_COLUMNS\[frame\]\)/);
  assert.doesNotMatch(room, /SPRITE_COLUMNS\[actionSet\.frames\[slot\]\]/);
  assert.match(room, /className="firework-sprite"/);
  assert.match(styles, /birthday-firework-alpha\.webp/);
  assert.match(styles, /@keyframes firework-pop/);
  assert.match(room, /key=\{flyby\.id\}/);
  assert.match(room, /setFlyby\(null\)/);
  assert.match(styles, /translateX\(calc\(50vw - 50%\)\)/);
  assert.match(room, /Hàng chờ đang trống/);
  assert.match(room, /playedWishes/);
  assert.match(room, /wish-history/);
  assert.match(room, /wish-list">\{wishes\.map/);
  assert.doesNotMatch(room, /wish-list">\{playedWishes/);
  assert.match(styles, /@keyframes wish-rise/);
  assert.match(styles, /min-height: 100cqh/);
  assert.doesNotMatch(room, /Math\.ceil\(6 \/ playedWishes\.length\)/);
  assert.match(room, /Array\.isArray\(incoming\)/);
  assert.match(room, /localStorage\.removeItem\(`birthday-wishes:/);
  assert.doesNotMatch(room, /wishKey|wishesRef|flyQueueRef|flyQueueCount|wishAction\.send\(wishes/);
  assert.match(room, /localStorage\.removeItem\(`birthday-polls:/);
  assert.doesNotMatch(room, /PollMessage|showPolls|poll-popover|Bình chọn|Kết thúc & lưu kết quả/);
  assert.doesNotMatch(styles, /\.poll-/);
  assert.match(room, /19:00 · 26\/09\/2026/);
  assert.match(room, /stage-invite/);
  assert.match(room, /setShowPhotoIntro\(true\)/);
  assert.match(styles, /\.stage-invite/);
  assert.match(room, /Khè Beer/);
  assert.match(room, /khe-beer-map-qr\.png/);
  assert.match(room, /maps\.app\.goo\.gl\/GjUqGVosSWSXcZWE8\?g_st=iz/);
  assert.match(styles, /\.intro-map-qr/);
  assert.match(room, /currentTrack\?\.bpm/);
  assert.match(room, /onEnded=\{playNextTrack\}/);
  assert.match(room, /tracks\[\(currentIndex \+ 1 \+ tracks\.length\) % tracks\.length\]/);
  assert.doesNotMatch(room, /<audio[^>]*\sloop(?:\s|=|>)/);
  assert.match(room, /usedAvatarIds/);
  assert.match(room, /stagePosition/);
  assert.match(room, /party-stage/);
  assert.match(room, /publishSpotlight/);
  assert.match(styles, /\.party-stage/);
  assert.match(room, /const x = 50/);
  assert.match(room, /HỒ SƠ CHỦ PHÒNG/);
  assert.match(room, /host=\{guest\.token === electedHostToken\}/);
  assert.match(room, /triggerAction\("toast"\)/);
  assert.match(room, /🍻<\/span>Nâng ly/);
  assert.match(room, /type RoomEffect = \{ type: "confetti" \| "toast"/);
  assert.match(room, /className="beer-toast-show"/);
  assert.match(styles, /@keyframes sprite-toast/);
  assert.doesNotMatch(styles, /action-toast::after|@keyframes toast-mugs/);
  assert.match(styles, /@keyframes beer-clink-left/);
  assert.match(styles, /@keyframes sprite-groove/);
  assert.match(styles, /@keyframes sprite-shuffle/);
  assert.match(styles, /@keyframes sprite-disco/);
  assert.doesNotMatch(room, /"spin"|Xoay người/);
  assert.doesNotMatch(styles, /action-spin|sprite-turn|rotateY\(180deg\)/);
  assert.doesNotMatch(room, /\bemote\b|action-clap/);
  assert.equal(playlist.length, 6);
  assert.doesNotMatch(room, /WASD|touch-dpad|onKeyDown/);
  assert.match(room, /localStorage/);
  assert.match(room, /trystero/);
  assert.match(room, /sendQuietly/);
  assert.doesNotMatch(room, /void \w+SendRef\.current/);
  assert.doesNotMatch(`${page}\n${layout}`, /codex-preview|SkeletonPreview/);
});
